### ISSUE TITLE
VxOpsCenter Overlay Plugin not rendering on complete view

### ISSUE THREAD

**Issue by vivekallgo** [pelcointegrations/VxPDK-SimplePlugin#1]
### We tried to create an independent plugin in VxOpsCenter using the sample code "VxPDK-SimplePlugin".

The sample is written in  WPF which appears within the VxOpsCenter Overlay Plugins. The screenshot of the plugin under development is Attached.
![vxop](https://user-images.githubusercontent.com/20203869/54011112-5bf28b80-4197-11e9-8054-842072a1b3dc.png)

As you can see that the sample plugin is not rendering in complete view. Please help.

**Comment by Klangen82** [comment]
Hi @vivekallgo I think the best way to get help on this matter is to use the http://pdn.pelco.com/forum instead.

**Comment by vivekallgo** [comment]
Thanks @Klangen82  I will check with forum.
